Feature/module5 react hooks
gcuatem/React-Mentoring-Program pull request #5
Opened 2024-04-03 03:11 UTC by gcuatem

2024-04-05 19:08 UTC, epam-kursikov approved these changes

2024-04-05 19:08 UTC, epam-kursikov commented on module-1/src/App.tsx
> +      <MovieListPage></MovieListPage>
```suggestion
      <MovieListPage />
```

2024-04-05 19:08 UTC, epam-kursikov commented on module-1/src/Components/MovieDetails/MovieDetails.tsx
> +export const MovieDetails = (props: any) => {
```suggestion
export const MovieDetails = () => {
```

2024-04-05 19:08 UTC, epam-kursikov commented on module-1/src/Components/MovieDetails/MovieDetails.tsx
> +    };
Don't mix async/await with fetch syntax. It's a simple case so probably async/await will be the easiest way to implement the functionality.

2024-04-05 19:08 UTC, epam-kursikov commented on module-1/src/Components/MovieDetails/MovieDetails.tsx
> +  const [isLoading, setIsLoading] = useState(false);
Much like you check the loading state, you should also track errors. Save the caught error in the state and show UI if anything went wrong during the request.

2024-04-05 19:08 UTC, epam-kursikov commented on module-1/src/Components/MovieDetails/MovieDetails.tsx
> +          src={movie?.poster_path}
Add an early return condition for cases when API call failed or if you don't have `movie` for any other reason. This way in the actual UI you will not need conditional chaining because you will already bail out if anything went wrong.

2024-04-05 19:08 UTC, epam-kursikov commented on module-1/src/Components/MovieDetails/MovieDetails.tsx
> +              key={i}
```suggestion
              key={g}
```

2024-04-05 19:08 UTC, epam-kursikov commented on module-1/src/Components/MovieListPage/MovieListPage.tsx
> +        await fetch(baseUrl)
Same as above, don't mix async/await with promise chaining.

2024-04-05 19:08 UTC, epam-kursikov commented on module-1/src/Components/MovieListPage/MovieListPage.tsx
> +  useEffect(() => {
You don't need effects here. In addition to my presentation I recommend reading through this article
https://react.dev/learn/you-might-not-need-an-effect

2024-04-05 19:08 UTC, epam-kursikov commented on module-1/src/Components/MovieTile/MovieTile.tsx
> +    <div key={movie.id} className="bg-custom_dark_gray  p-3">
```suggestion
    <div className="bg-custom_dark_gray  p-3">
```

2024-04-05 19:08 UTC, epam-kursikov commented on module-1/src/Components/MovieTile/MovieTile.tsx
> +          <p key={i} className=" text-slate-300  px-2 text-xs ml-1">
```suggestion
          <p key={g} className=" text-slate-300  px-2 text-xs ml-1">
```

2024-04-05 19:08 UTC, epam-kursikov commented on module-1/src/Components/Search/Search.tsx
> +    await setSearchQuery(event.target.value);
```suggestion
  const handleInputChange = (
    event: React.ChangeEvent<HTMLInputElement>
  ) => {
    setSearchQuery(event.target.value);
```

2024-04-05 19:08 UTC, epam-kursikov commented on module-1/src/Components/SortControl/SortControl.tsx
> +  const capitalize = (s: string) =>
You can use CSS for capitalization https://developer.mozilla.org/en-US/docs/Web/CSS/text-transform

2024-04-05 23:33 UTC, gcuatem commented on module-1/src/App.tsx
> +      <MovieListPage></MovieListPage>
done

2024-04-05 23:35 UTC, gcuatem commented on module-1/src/Components/MovieDetails/MovieDetails.tsx
> +export const MovieDetails = (props: any) => {
fixed

2024-04-05 23:54 UTC, gcuatem commented on module-1/src/Components/MovieDetails/MovieDetails.tsx
> +    };
fixed

2024-04-06 00:28 UTC, gcuatem commented on module-1/src/Components/MovieDetails/MovieDetails.tsx
> +  const [isLoading, setIsLoading] = useState(false);
done

2024-04-06 00:31 UTC, gcuatem commented on module-1/src/Components/MovieDetails/MovieDetails.tsx
> +          src={movie?.poster_path}
done

2024-04-06 00:35 UTC, gcuatem commented on module-1/src/Components/MovieDetails/MovieDetails.tsx
> +              key={i}
fixed

2024-04-07 01:51 UTC, gcuatem commented on module-1/src/Components/MovieListPage/MovieListPage.tsx
> +        await fetch(baseUrl)
fixed

2024-04-07 01:52 UTC, gcuatem commented on module-1/src/Components/MovieListPage/MovieListPage.tsx
> +  useEffect(() => {
fixed

2024-04-07 01:54 UTC, gcuatem commented on module-1/src/Components/MovieTile/MovieTile.tsx
> +    <div key={movie.id} className="bg-custom_dark_gray  p-3">
fixed

2024-04-07 01:54 UTC, gcuatem commented on module-1/src/Components/MovieTile/MovieTile.tsx
> +          <p key={i} className=" text-slate-300  px-2 text-xs ml-1">
fixed

2024-04-07 01:56 UTC, gcuatem commented on module-1/src/Components/Search/Search.tsx
> +    await setSearchQuery(event.target.value);
done

2024-04-07 02:05 UTC, gcuatem commented on module-1/src/Components/SortControl/SortControl.tsx
> +  const capitalize = (s: string) =>
fixed

2024-04-12 01:49 UTC, epam-kursikov requested changes

2024-04-12 01:49 UTC, epam-kursikov commented on module-1/src/Components/MovieDetails/MovieDetails.tsx
> +  const [Errormsg, setErrorMsg] = useState();
minor
```suggestion
  const [errorMsg, setErrorMsg] = useState();
```

2024-04-12 01:49 UTC, epam-kursikov commented on module-1/src/Components/MovieListPage/MovieListPage.tsx
> +    fetch(newUrl)
Fetch should not be in `useMemo`. A correct but hacky approach will be to build the URL in `useMemo` and have it as a dependency for `useEffect`. That effect will call the API.

Ideally you should have a single call in an effect for the initial load. Calls for changes in sorting or filtration should be performed directly from event handlers.

2024-04-12 18:32 UTC, epam-kursikov requested changes

2024-04-12 18:32 UTC, epam-kursikov commented on module-1/src/Components/MovieListPage/MovieListPage.tsx
> +  const buildUrl = useMemo(() => {
We don't need a memo for the URL anymore, we need a function that will build the URL based on the input params.

2024-04-12 18:32 UTC, epam-kursikov commented on module-1/src/Components/MovieListPage/MovieListPage.tsx
> +      .finally(() => setIsLoading(false));
Reuse `fetchUrl`
```suggestion
    fetchUrl(defaultURL);
```
where `defaultURL` will be built by the same `buildURL` function with some default parameters.

2024-04-12 18:32 UTC, epam-kursikov commented on module-1/src/Components/MovieListPage/MovieListPage.tsx
> +    newUrl += genre === "All" ? EMPTYSTRING : genre_str;
Replace copy pasted code with `buildURL`.

2024-04-16 00:58 UTC, merged